### ISSUE TITLE
perl6.org/downloads needs links to "finished builds"

### ISSUE THREAD

**Issue by COMBORICO** [perl6/perl6.org#109]
Something similar to this: https://rakudo.org/files/star/third-party 

The idea is that most newbies don't know how to build from scratch.  I myself am still struggling with PATH.  I did it once or twice the last six months, and forgot how to do it sense then.  

Having something that a user can easily download and install is absolute key to the growth of budding programmers in any programming language.  

The page should also briefly explain that "finished builds" are the easiest way to install Perl6.  How else would they know unless you tell them?

**Comment by Tyil** [comment]
> Having something that a user can easily download and install is absolute key to the growth of budding programmers in any programming language.

We have tools to ease the installation already: [Rakudup](https://rakudup.github.io/) and [LoneStar](https://github.com/tyil/lonestar). In the case of LoneStar, it also comes with a tool to set up the `PATH` for you.

Additionally, the Ubuntu 18.04 includes Rakudo Perl 6 in its default repositories. I'd preferably see up-to-date packages appearing in more default distro repos. This would be the best solution for users of all levels.

**Comment by niner** [comment]
openSUSE currently ships 2018.03 and soon 2018.04 and that may even make it into SLES 15

**Comment by nxadm** [comment]
[rakudo-pkg](https://github.com/nxadm/rakudo-pkg) does provide a [script](https://github.com/nxadm/rakudo-pkg/blob/master/docker/add-perl6-to-path) to set the PATH. It's documented [here](https://github.com/nxadm/rakudo-pkg#set-the-path). You only need to do this on your first install (and you can forget about it).

**Comment by nxadm** [comment]
I don't think this ticket should refer to the perl6 site. In case one of the packaging/build efforts doesn't handle this correctly, an issue should be raised there. 

Closing this issue, feel free to reopen.
