### ISSUE TITLE
Perl6 FAQ - update information

### ISSUE THREAD

**Issue by asb-capfan** [perl6/perl6.org#11]
Hi!

There is some information in the Perl 6 FAQ here: http://www.perl6.org/archive/faq.html 

For example: "That said, there is a release date for Rakudo: In Q2 2010 Patrick Michaud will release a useful and usable (but not feature complete) Perl 6 compiler".
2010 has already passed, but I honestly don't know about this Topic. Did the release happen? Does anybody know? Otherwise, we could just remote the section and Point to pugs & parrot.

Also, planetsix.perl.org which is linked in section "Is there a release date set for perl 6.0 ?" is dead. Is it just down or can we remove it fro the list?

**Comment by zoffixznet** [comment]
I think the above merge fixes the linking issue and I'm about to commit a change that makes it more obvious that we're reading an archive. Together, I think the changes take care of this issue.
