### ISSUE TITLE
The link https://perl6.org/community/irc is broken

### ISSUE THREAD

**Issue by kjkuan** [perl6/perl6.org#127]
The link returns `not found`. The link is visible under the https://perl6.org/community page.

**Comment by lichtkind** [comment]
looks fixed now

**Comment by Altai-man** [comment]
>not found

for me.

Related https://github.com/perl6/problem-solving/issues/9

**Comment by lukasvalle** [comment]
Same for rosetta code on community page. Both files are there, but are are named .html. 
[irc](https://perl6.org/community/irc.html) and [rosettacode](https://perl6.org/community/rosettacode.html). 
As this was working, maybe there was a rewrite rule somewhere that is missing now.

**Comment by rba** [comment]
looks fixed. keep it for myself to be able to double-check after hosting is moved to a permanent solution.

**Comment by rba** [comment]
fixed.
