### ISSUE TITLE
problem with website

### ISSUE THREAD

**Issue by dataf3l** [perl6/perl6.org#137]
on this url:

https://perl6.org/downloads/

I ran these instructions:

% wget https://rakudo.perl6.org/downloads/star/rakudo-star-2019.03.tar.gz
% tar xfz rakudo-star-2019.03.tar.gz
% cd rakudo-star-2019.03
% perl Configure.pl --gen-moar --make-install --prefix ~/rakudo

as per the website.

the instructions no longer work, the URL returns HTML, not a GZIP file,  the new URL is:

https://rakudo.perl6.org/dl/star/rakudo-star-2018.10.tar.gz

which means the rest of the commands don't work either, so I had to think, and that was hard for me.

As a curl user, it was posible for me to navigate the process, since I noticed the filesize downloaded by the thing was not what I expected, but perhaps a more novice user would waste a lot more time debugging the problem.

let's make it easy by changing the site.

**Comment by AlexDaniel** [comment]
Ping @rba.

**Comment by AlexDaniel** [comment]
> let's make it easy by changing the site.

We should fix the link by redirecting it correctly, it's possible that there are other resources that rely on the same url.

**Comment by rba** [comment]
Should be fixed. Please check.

**Comment by dataf3l** [comment]
The URL now works.

**Comment by AlexDaniel** [comment]
Thanks!
