### ISSUE TITLE
Remove links to the wiki

### ISSUE THREAD

**Issue by coke** [perl6/perl6.org#14]
The wiki was setup a long time ago before we had any infrastructure; there's a lot of stale information there that we keep up to date on perl6.org itself.
- remove any links to the wiki from perl6.org
- cleanup the front page of the wiki so it has a link to perl6.org (+ camelia if you like), and a note that the wiki is "no longer actively maintained, please use perl6.org to look for information about perl 6"

**Comment by coke** [comment]
Looks like the links to the wiki are gone.

**Comment by zoffixznet** [comment]
Yeah, I think this was when: https://github.com/perl6/perl6.org/commit/471fc02bbdc4d3a52a48ba7b2b1fa03176dbfac7

**Comment by zoffixznet** [comment]
Anyone got the keys to the wiki so we could take care of this and close the issue:
>cleanup the front page of the wiki so it has a link to perl6.org (+ camelia if you like), and a note that the wiki is "no longer actively maintained, please use perl6.org to look for information about perl 6"

**Comment by coke** [comment]
I have a login to that site, but apparently not rights to edit. I'll open a ticket with someone on the foundation team.

**Comment by zoffixznet** [comment]
> I have a login to that site, but apparently not rights to edit. I'll open a ticket with someone on the foundation team.

How did that go? I see [the wiki](http://www.perlfoundation.org/perl6/index.cgi?perl_6) says:

> We're currently working on replacing all pages with suitable links to current and up-to-date locations for informations you used to find here.

is that the updated version or is that still from that outdated time?

**Comment by coke** [comment]
I... cannot recall. I'll start over on this task.

**Comment by lukasvalle** [comment]
Wiki seems to be gone now:


> 404 -  Error - Page Not Found

> Please check the URL.

> Otherwise, click here to be redirected to the homepage.

Redirect does then go to the perlfoundation web site.
