### ISSUE TITLE
Fix DNS server configuration 

### ISSUE THREAD

**Issue by andreoss** [perl6/perl6.org#17]
Every sub-domain resolves and points to design.perl6.org 

% dig anything.perl6.org  

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> anything.perl6.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24305
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;anything.perl6.org.            IN      A

;; ANSWER SECTION:
anything.perl6.org.     3600    IN      A       213.95.82.53

;; Query time: 151 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Sat May 23 19:56:17 2015
;; MSG SIZE  rcvd: 52

**Comment by zoffixznet** [comment]
IIRC, this is done on purpose, so it's easier for us to add extra subdomains, if we need any.
