### ISSUE TITLE
Spunky

### ISSUE THREAD

**Issue by pjcj** [perl6/perl6.org#32]
Any chance of choosing a different word?  It has an entirely different meaning for much of the English-speaking world.  See http://separatedbyacommonlanguage.blogspot.ch/2011/08/spunk-and-spunky.html

Perhaps "spirited"?

**Comment by zoffixznet** [comment]
:+1: even though I'm in Canada, I've watched enough British comedies to associate with the slang meaning, rather than what was intended.

**Comment by jonathanstowe** [comment]
It's the inner Sid James speaking, I actually quite like the unintended double entendre, hur fnurgh.

**Comment by MattOates** [comment]
Can I put 'plucky' out there as an alternative?

**Comment by uvtc** [comment]
Oooh, MattOates, nice word choice. :+1:

**Comment by labster** [comment]
I'd like to bikesh^W suggest moxious, because Camelia definitely has moxie.

**Comment by stmuk** [comment]
As a native British English speaker I'd never heard of "moxie" and had to
google it.

I like "plucky" but wonder if the whole paragraph should be revised as we
move from pre-release phase.

On 7 October 2015 at 04:10, Brent Laabs <notifications@github.com> wrote:

> I'd like to bikesh^W suggest moxious, because Camelia definitely has moxie.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/perl6.org/issues/32#issuecomment-146066544>.
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>
