### ISSUE TITLE
doc.perl6.org not prominent enough

### ISSUE THREAD

**Issue by coke** [perl6/perl6.org#48]
/documentation has doc.perl6.org, but it's buried.

It needs to be the most obvious thing to click on.

**Comment by MadcapJake** [comment]
One though would be to just give it a block of its own.

A slightly more radical though: why not make the main nav bar `documentation` link directly to `doc.perl6.org` and have a separate nav 'resources` link for that page.

**Comment by AlexDaniel** [comment]
Perhaps current “Documentation” link should be renamed to “Resources”?

**Comment by coke** [comment]
I prefer keeping a /documentation page. There are more kinds of docs than our equivalent of javadocs, it's just the thing people are most likely looking for.

**Comment by AlexDaniel** [comment]
From https://github.com/perl6/doc#vision:

> I want p6doc and doc.perl6.org to become the No. 1 resource to consult when you want to know something about a Perl 6 feature, be it from the language, or built-in types and routines.

I think that it is a good idea to point directly to “No. 1 resource” without any intermediate steps.

“more kinds of docs” sounds like “other resources”. Do you actually classify all these links on /documentation as documentation? If not, what would you recommend to keep there?

**Comment by uvtc** [comment]
Are the Synopses still current? Or are they in the process of slowly being replaced by the docs at doc.perl6.org?

If the Synopses are being replaced, then maybe they no longer deserve their own top-level "Design" heading at the top of perl6.org. If so, then the stuff under "Design" could be placed in its own block under the Documentation tab, rounding it out to an even 6 ( **6! ;)** ) and the Design tab could simply be removed.

Then maybe change the title block (with the grey background) under the Documentation tab to something like:

> "**Perl 6** Documentation
>
> \<div class="you-know-you-want-to-click-this">The [Official Perl 6 documentation].\</div>"

and then, in the block below *that* (the one containing the 6 blocks), start it off with its own bar across the top:

> "<b>Other Documentation</b>
>
> Some of the documentation referenced here is incomplete and/or outdated. If you come across
> information you suspect is outdated, please consider helping the authors to update it, let us know
> about it, or help us to improve this page by providing links to better information."
