### ISSUE TITLE
Up-to-date rakudo release notice

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/perl6.org#52]
Main page says:
> Perl 6 Language Version 6.c and Perl 6 Rakudo Star 2016.04 Released!

But we already have 2016.07. Can we somehow ensure that it is always showing the proper information? For example, it may be part of the release process.

**Comment by zoffixznet** [comment]
Hi,

There appears to be a bit of confusion: Rakudo Star 2016.07 has *not* been released yet. The release manager has only advertised the RC (Release Candidate) so far. When release happens, the deliverables will be available on [http://rakudo.org/downloads/star/](http://rakudo.org/downloads/star/)

The [Rakudo Star release guide](https://github.com/rakudo/star/blob/master/tools/star/release-guide.pod) does already mention updating perl6.org during release (step 13)

**Comment by AlexDaniel** [comment]
\*facepalm\* I did not notice the word “Star”.

I am inclined to close this, but there's a question – should we mention regular rakudo releases on the homepage?

**Comment by zoffixznet** [comment]
To quote Step 19 from Rakudo [release guide](https://github.com/rakudo/rakudo/blob/nom/docs/release_guide.pod):

> To avoid public confusion with Rakudo Star releases, we now publish compiler release announcements ONLY to perl6-compiler@perl.org. (We may restart widespread announcements of compiler releases once they are known, or we may begin publishing a single announcement for both.)
