### ISSUE TITLE
Resources Tab Nav Issues

### ISSUE THREAD

**Issue by zoffixznet** [perl6/perl6.org#57]
When clicking on [resources tab](), the `Documentation` tab also shows up as active page. 

![untitled](https://cloud.githubusercontent.com/assets/5747918/19015513/0c0796d0-87d4-11e6-86f5-965f983511a2.png)

Marking for Hacktoberfest.

The fix, I believe, involves replacing [the `doc` nav marker](https://github.com/perl6/perl6.org/blob/dc08a964b8dd21f19b938494eff95d1d8df01ab5/source/documentation/index.html#L3) with `res` and changing it to `res` in [in the nav file](https://github.com/perl6/perl6.org/blob/master/includes/menu-nav#L23) as well.

Also, for consistency, easier maintenance, and lesser confusion, it's worth renaming the [`documentation` directory](https://github.com/perl6/perl6.org/tree/master/source/documentation) to `resources` as it's now called, fixing [the link in the nav](https://github.com/perl6/perl6.org/blob/master/includes/menu-nav#L24), and pinging one of the site admins (I can do it when PR is ready) to add an .htaccess redirect to the new page.

**Comment by sandmanx** [comment]
On it !

**Comment by josiahdahl** [comment]
I've submitted a pull request for this issue.
