### ISSUE TITLE
Recommend spacemacs as one of the editors

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/perl6.org#83]
Page in question: https://perl6.org/whatever/

It already talks about vim and emacs, but interestingly a viable alternative for vim users is https://github.com/syl20bnr/spacemacs. So it's emacs+extra stuff+vim keybindings. It seems that it already has a perl6 layer (using emacs perl6-mode), so everything should work just fine.

See also:
* https://github.com/syl20bnr/spacemacs/issues/5019
* https://github.com/syl20bnr/spacemacs/pull/8493

**Comment by tibi77** [comment]
I can do it :D
