### ISSUE TITLE
Recommend neovim as one of the editors

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/perl6.org#84]
Neovim does have a perl6 syntax file, but it is outdated: https://github.com/neovim/neovim/blob/master/runtime/syntax/perl6.vim

In any case, maybe it is actually usable? Perhaps somebody can try it and if it works even a little bit, we can list it too.

**Comment by Tyil** [comment]
afaik this is available in normal vim too, but there exists https://github.com/vim-perl/vim-perl6.git which should work on both.

**Comment by Tyil** [comment]
I'll try compiling `neovim` and give it a whirl, and see if the `vim-perl/vim-perl6.git` bundle works nicely with it as well. If the results are positive, I'll add it as a recommendation.
